---
title: "Pm10 Analysis"
author: "Divyanshu Jhawar"
date: "26 April 2020"
output: html_document
---

Libraries
```{r libr,results="hide",warning=FALSE,message=FALSE}

#install.packages("vars")

library(imputeTS)
library(ggplot2)
library(forecast)
library(tseries)
library(tidyverse)
library(lubridate)
library(astsa)
library(vars)
```

Reading file....
```{r}
d <- read.csv("PRSA/PRSA_Data_Aotizhongxin_20130301-20170228.csv")

#summary(d)

```

Counting NA values
```{r}

sapply(d, function(x) sum(is.na(x)))

```

Filling in missing values
```{r}
data <- na_ma(d, k = 10, weighting = "simple")
sapply(data, function(x) sum(is.na(x)))
```

Defining variables
```{r}
NO2 <- data$NO2
SO2 <- data$SO2
CO <- data$CO
O3 <- data$O3

PM2.5 <- data$PM2.5
PM10 <- data$PM10
```



Plotting the variables wrt time
```{r}
plot(PM10,type="l",xlab="time")

```


GGplot
```{r}


ggplot(data, aes(x=NO2, y=PM2.5), color="steelblue") + geom_line()

```



Converting (year,month,date) -> (y-m-d) format
```{r}
data$date <- as.Date(with(data, paste(year, month, day,sep="-")), "%Y-%m-%d")

```
